### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by shermes641** [martinez099/ordershop#1]
Thanks for a great example.

I've played with running this in Kubernetes.
And I have a strange problem.

PUTS & DELETES do not seem to work.

My code works fine using docker-compose up, but in Kubernetes tests 5,6,7,8,9 fail

Any ideas why I would be able to create the data but not change it ?

I can create a repo with my code if you want to look into this further.

======================================================================
FAIL: test_5_update_second_order (client.client.OrderShopTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\_KUBE\uptime99\ordershop\client\client.py", line 309, in test_5_update_second_order
    self.assertEqual(orders[1]['product_ids'][0], order['product_ids'][0])
AssertionError: '669a974d-dd49-4334-b6a8-7a1e1d5f1e4e' != '0a30c176-0ed6-4e7a-acb1-a67a55268935'
- 669a974d-dd49-4334-b6a8-7a1e1d5f1e4e
+ 0a30c176-0ed6-4e7a-acb1-a67a55268935

======================================================================
FAIL: test_6_delete_third_order (client.client.OrderShopTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\_KUBE\uptime99\ordershop\client\client.py", line 326, in test_6_delete_third_order
    self.assertIsNone(json.loads(rsp))
AssertionError: {'id': 'e43a81dc-d894-4a3c-a410-d5cfc1cb1666', 'product_ids': ['5cb47271-1efa-4f62-bc1d-6568ed376626', 'cc7eee15-2efe-46e1-9573-1b07d2c9a6ca', '0a30c176-0ed6-4e7a-acb1-a67a55268935', '0b505619-6a5c-40db-8e89-cbd59e39e50e', '244bf55e-514b-4342-9970-e822193f52fe'], 'customer_id': 'a2d5c94e-1ee6-4acf-b6ae-433c2b69709b'} is not None

======================================================================
FAIL: test_7_delete_third_customer (client.client.OrderShopTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\_KUBE\uptime99\ordershop\client\client.py", line 344, in test_7_delete_third_customer
    self.assertIsNone(json.loads(rsp))
AssertionError: {'id': 'ea301b0b-67fb-49c0-a417-4dc1fed79750', 'name': 'Ylauahemoj', 'email': 'ylauahemoj@server.com'} is not None

======================================================================
FAIL: test_9_get_unbilled_orders (client.client.OrderShopTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\_KUBE\uptime99\ordershop\client\client.py", line 368, in test_9_get_unbilled_orders
    self.assertEqual(len(unbilled), 8)
AssertionError: 9 != 8

**Comment by martinez099** [comment]
Hi,
to investigate this, please push a separate branch and I'll have a look at it.
Cheers

**Comment by shermes641** [comment]
Will do
