### ISSUE TITLE
unit test fails assertion

### ISSUE THREAD

**Issue by kerneljake** [martinez099/ordershop#4]
I consistently get a failure in the final test, test_j_sent_mails .

```
$ python3 -m unittest tests/unit.py
.........F
======================================================================
FAIL: test_j_sent_mails (tests.unit.OrderShopTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jake/Redislabs-Solution-Architects/ordershop-martinez099/tests/unit.py", line 197, in test_j_sent_mails
    self.assertEqual(len(sent_mails), 22)
AssertionError: 18 != 22
----------------------------------------------------------------------
Ran 10 tests in 15.791s
FAILED (failures=1)
```
I do a FLUSHDB between invocations of the command line to get this result.
If I don't do a FLUSHDB, then subsequent invocations produce even more errors across multiple unit tests.
I suspect the sleep() calls.  I am running this on "older" mac hardware, and it feels like a timing issue.

**Comment by martinez099** [comment]
Hi Jake,

thanks for getting in touch.

A FLUSHDB is indeed necessary before each test execution to reset the DB.

The failed unit test is about the sent emails, which is a timing issue, you can ignore it.

Cheers, Martin
